[package]
name = "rp2040"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded_common = {path = "../embedded_common"}
tokio.workspace = true
tokio-serial = "5.4.5"
tracing.workspace = true
udev = "0.9.1"
