[package]
name = "gputter-core"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0"
bytemuck.workspace = true
nalgebra.workspace = true
anyhow.workspace = true
# static_assertions.workspace = true
# crossbeam.workspace = true
pollster = "0.3.0"