[package]
name = "lunabot-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
ares-bt = { workspace = true }
nalgebra = { workspace = true }
common = { path = "../common" }
tracing = { workspace = true }
k = { workspace = true }
simple-motion.workspace = true