[package]
name = "lunasim-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { workspace = true }
crossbeam = { workspace = true }
# tasker = { workspace = true }
common = { path = "../common" }